/* Cambios hechos desde la rama secundaria
*/

package literapp;

import javax.swing.UIManager;

/**
 * 
 * Ventana principal de la aplicación de libros. Se utiliza el patrón de diseño 
 * Singleton en cada una de las ventanas internas para evitar abrir múltiples 
 * instancias de cada una.
 *
 * @author gabag
 */
public class PrincipalJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }
    
    private void crearTablas() {
        String consulta = 
                "CREATE TABLE IF NOT EXISTS generos("
                + "     id INT(3) PRIMARY KEY AUTO_INCREMENT, "
                + "     genero VARCHAR(30), "
                + "     descripcion TEXT"
                + "); "
                + "CREATE TABLE IF NOT EXISTS libros("
                + "     id INT(4) PRIMARY KEY AUTO_INCREMENT, "
                + "     titulo VARCHAR(100), "
                + "     autor VARCHAR(100), "
                + "     publicacion INT(4), "
                + "     genero INT(3), "
                + "     leido BOOLEAN, "
                + "     descripcion TEXT, "
                + "     comentario TEXT, "
                + "     portada MEDIUMBLOB, "
                + "     FOREIGN KEY (genero) REFERENCES generos(id) "
                + "     ON DELETE SET NULL ON UPDATE CASCADE"
                + ");";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuLibros = new javax.swing.JMenu();
        jMenuItemLibrosAnadir = new javax.swing.JMenuItem();
        jMenuItemLibrosLista = new javax.swing.JMenuItem();
        jMenuGeneros = new javax.swing.JMenu();
        jMenuItemGenerosLista = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAyudaAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LiterApp");
        setResizable(false);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/literapp/res/logo.png"))); // NOI18N

        jMenuLibros.setText("Libros");

        jMenuItemLibrosAnadir.setText("Añadir libro");
        jMenuItemLibrosAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibrosAnadirActionPerformed(evt);
            }
        });
        jMenuLibros.add(jMenuItemLibrosAnadir);

        jMenuItemLibrosLista.setText("Lista de libros");
        jMenuItemLibrosLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibrosListaActionPerformed(evt);
            }
        });
        jMenuLibros.add(jMenuItemLibrosLista);

        jMenuBarPrincipal.add(jMenuLibros);

        jMenuGeneros.setText("Géneros");

        jMenuItemGenerosLista.setText("Lista de géneros");
        jMenuItemGenerosLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerosListaActionPerformed(evt);
            }
        });
        jMenuGeneros.add(jMenuItemGenerosLista);

        jMenuBarPrincipal.add(jMenuGeneros);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAyudaAcerca.setText("Acerca de");
        jMenuAyuda.add(jMenuItemAyudaAcerca);

        jMenuBarPrincipal.add(jMenuAyuda);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLibrosListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibrosListaActionPerformed
        // TODO add your handling code here:
        ListaJFrame.getInstance().setVisible(true);
    }//GEN-LAST:event_jMenuItemLibrosListaActionPerformed

    private void jMenuItemLibrosAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibrosAnadirActionPerformed
        // TODO add your handling code here:
        LibrosJFrame.getInstance().setVisible(true);
    }//GEN-LAST:event_jMenuItemLibrosAnadirActionPerformed

    private void jMenuItemGenerosListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerosListaActionPerformed
        // TODO add your handling code here:
        GenerosJFrame.getInstance().setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerosListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Look and feel */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuGeneros;
    private javax.swing.JMenuItem jMenuItemAyudaAcerca;
    private javax.swing.JMenuItem jMenuItemGenerosLista;
    private javax.swing.JMenuItem jMenuItemLibrosAnadir;
    private javax.swing.JMenuItem jMenuItemLibrosLista;
    private javax.swing.JMenu jMenuLibros;
    // End of variables declaration//GEN-END:variables
}
